import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import type { SimpleGit } from 'simple-git';
import { parseMarkdown } from './frontmatter.js';
import { walkMarkdown } from './indexer.js';
import type { Logger } from './db.js';
import type { CaveatConfig } from './config.js';
import type { ResolvedPaths } from './paths.js';
import { classifyVisibility } from './visibility.js';
import { createGit } from './gitRuntime.js';
import { readSealedHeader, sealBundle, unsealBundle } from './sealedBundle.js';
import { createKeyserverKeyProvider, normalizeKeyserverUrl, type ContentKeyProvider } from './sealedKeys.js';
import {
  loadPublishAllow,
  publishSelfIdentityTokens,
  PublishScanError,
  savePublishAllow,
  scanPublishFiles,
} from './publishScan.js';

export interface PublishFile { relPath: string; content: Buffer; showcase: boolean; }
export interface PublishInvalid { relPath: string; reason: string; }
export interface PublishSet { files: PublishFile[]; invalid: PublishInvalid[]; }
export interface PublishChanges {
  lines: string[];
  added: number;
  modified: number;
  deleted: number;
}

const BUNDLE_RELPATH = 'bundle/entries.caveat';
const TMP_BRANCH = 'caveat-publish-tmp';

export function collectPublishSet(entriesDir: string): PublishSet {
  const files: PublishFile[] = [];
  const invalid: PublishInvalid[] = [];
  if (!existsSync(entriesDir)) return { files, invalid };
  for (const path of walkMarkdown(entriesDir)) {
    const relPath = relative(entriesDir, path).replace(/\\/g, '/');
    const content = readFileSync(path);
    try {
      const parsed = parseMarkdown(content.toString('utf-8'));
      const visibility = classifyVisibility(parsed.frontmatter.visibility);
      if (visibility === 'public') files.push({
        relPath,
        content,
        showcase: (parsed.frontmatter as unknown as { showcase?: unknown }).showcase === true,
      });
      else if (visibility === 'invalid') invalid.push({ relPath, reason: 'visibility must be exactly public or private' });
    } catch (err) {
      invalid.push({ relPath, reason: err instanceof Error ? err.message : String(err) });
    }
  }
  return { files, invalid };
}

export async function preparePublishMirror(opts: { mirrorDir: string; target: string; git?: SimpleGit }): Promise<void> {
  const git = opts.git ?? createGit();
  if (!existsSync(opts.mirrorDir)) {
    mkdirSync(dirname(opts.mirrorDir), { recursive: true });
    await git.clone(opts.target, opts.mirrorDir);
  } else {
    const mirrorGit = createGit(opts.mirrorDir);
    const old = (await mirrorGit.raw(['remote', 'get-url', 'origin'])).trim();
    if (old !== opts.target) {
      throw new Error(`publish mirror points at ${old} but publishTarget is ${opts.target} — remove ${opts.mirrorDir} and re-run`);
    }
  }
  const mirrorGit = createGit(opts.mirrorDir);
  await mirrorGit.raw(['fetch', '--prune', 'origin']);
  const head = (await mirrorGit.raw(['symbolic-ref', '--quiet', 'refs/remotes/origin/HEAD']).catch(() => '')).trim();
  // symbolic-ref は rc=0 のまま dangling ref 名を返し続けることがある: 非空 remote
  // から clone したミラーは origin/HEAD symref を持つが、remote を空にして作り直すと
  // 次の fetch --prune で origin/<branch> が消え、symref 自体は残ったまま参照先だけ
  // 消える。ここで無条件に reset --hard すると unknown revision で毎回死に、ミラーを
  // 手で消すまで publish が恒久的に不能になる。rev-parse --verify で実際に解決可能か
  // を確認し、解決不能なら reset を skip する。これは隠れ fallback ではない — skip
  // すると後段の remoteBranchSha が null を返し、「remote branch differs or is
  // missing」ゲート（既存の再 push 経路）に正しく倒れる構造上の判断。
  const headResolvable = head
    ? (await mirrorGit.raw(['rev-parse', '--verify', '--quiet', head]).catch(() => '')).trim() !== ''
    : false;
  if (head && headResolvable) await mirrorGit.reset(['--hard', head]);
  // git clean -ffdx: remove any untracked debris (incl. ignored) a crashed
  // prior run may have left, so it cannot be re-committed and leaked (C4).
  await mirrorGit.raw(['clean', '-ffdx']);
}

export function buildSealedReadme(fileCount: number, files: PublishFile[]): string {
  const lines = [
    '# Caveat-Public',
    '',
    'This repository is generated by `caveat publish`. Do not edit it by hand.',
    '',
    'Subscribe with:',
    '',
    '```sh',
    'npm i -g caveat-cli && caveat community add <https URL or username>',
    '```',
    '',
    '## Threat Model',
    '',
    'This sealed mirror is designed to block casual browsing, copying, LLM training crawlers, and GitHub-hosted AI training from reading entry text directly.',
    '',
    'It is not designed to stop a motivated human from analyzing the published bundle or client code.',
    '',
    `Public entries: ${fileCount}`,
    '',
    'Caveat: https://github.com/kitepon/Caveat',
    '',
  ];
  // localeCompare は ICU/ロケールに依存し端末ごとに順序が変わり得る。README は publish
  // の no-op 判定（既存 README との文字列比較）に参加するため、順序が揺れると内容が
  // 同じでも README 差分で端末間 push し合う ping-pong を起こす。sealedBundle.ts の
  // canonicalizeFiles と同じ UTF-8 バイト列比較で locale 非依存に統一する。
  const showcase = files
    .filter((f) => f.showcase)
    .sort((a, b) => Buffer.compare(Buffer.from(a.relPath, 'utf-8'), Buffer.from(b.relPath, 'utf-8')));
  if (showcase.length) {
    lines.push('## Showcase', '');
    for (const file of showcase) {
      lines.push(`### ${file.relPath}`, '', parseMarkdown(file.content.toString('utf-8')).body.trimEnd(), '');
    }
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

// The mirror is a pure generated artifact: every path except .git is replaced
// on each publish. Sealed mirrors contain only README.md and one bundle file.
export function writeSealedMirror(opts: { mirrorDir: string; bundle: Buffer; readme: string }): void {
  for (const item of readdirSync(opts.mirrorDir, { withFileTypes: true })) {
    if (item.name === '.git') continue;
    rmSync(join(opts.mirrorDir, item.name), { recursive: true, force: true });
  }
  const bundlePath = join(opts.mirrorDir, BUNDLE_RELPATH);
  mkdirSync(dirname(bundlePath), { recursive: true });
  writeFileSync(join(opts.mirrorDir, 'README.md'), opts.readme, 'utf-8');
  writeFileSync(bundlePath, opts.bundle);
}

function* walkAllFiles(root: string): Generator<string> {
  for (const item of readdirSync(root, { withFileTypes: true })) {
    if (item.name === '.git') continue;
    const full = join(root, item.name);
    if (item.isDirectory()) yield* walkAllFiles(full);
    else yield full;
  }
}

export function verifySealedMirror(opts: {
  mirrorDir: string;
  bundle: Buffer;
  contentKey: Buffer;
  expectedFileCount: number;
  readme: string;
}): { fileCount: number } {
  const files = [...walkAllFiles(opts.mirrorDir)].map((path) => relative(opts.mirrorDir, path).replace(/\\/g, '/')).sort();
  const expected = ['README.md', BUNDLE_RELPATH];
  if (files.length !== expected.length || files.some((file, index) => file !== expected[index])) {
    throw new Error(`publish mirror verification failed:\nunexpected sealed mirror tree: ${files.join(', ') || '(empty)'}`);
  }
  const diskReadme = readFileSync(join(opts.mirrorDir, 'README.md'), 'utf-8');
  if (diskReadme !== opts.readme) {
    throw new Error('publish mirror verification failed: README.md content changed after generation');
  }
  const diskBundle = readFileSync(join(opts.mirrorDir, BUNDLE_RELPATH));
  if (!diskBundle.equals(opts.bundle)) {
    throw new Error('publish mirror verification failed: sealed bundle bytes changed after generation');
  }
  const unsealed = unsealBundle(diskBundle, opts.contentKey);
  const bad: string[] = [];
  for (const file of unsealed.files) {
    try {
      const visibility = classifyVisibility(parseMarkdown(file.content.toString('utf-8')).frontmatter.visibility);
      if (visibility !== 'public') bad.push(`${file.relPath}: visibility is ${visibility}`);
    } catch (err) {
      bad.push(`${file.relPath}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  if (unsealed.files.length !== opts.expectedFileCount) {
    bad.push(`file count mismatch: expected ${opts.expectedFileCount}, got ${unsealed.files.length}`);
  }
  if (bad.length) throw new Error(`publish mirror verification failed:\n${bad.join('\n')}`);
  return { fileCount: unsealed.files.length };
}

export interface PublishOwnOptions {
  paths: Pick<ResolvedPaths, 'caveatHome' | 'entriesDir' | 'publishMirrorDir'>
    & Partial<Pick<ResolvedPaths, 'knowledgeRepo'>>;
  config: CaveatConfig;
  logger: Logger;
  confirmImpl: (question: string) => boolean;
  keyProvider?: ContentKeyProvider;
  isTty?: () => boolean;
  dryRun?: boolean;
  yes?: boolean;
  allow?: string[];
  saveAllow?: boolean;
}
export interface PublishResult { fileCount: number; changed: boolean; dryRun: boolean; }

function sha256(content: Buffer): string {
  return createHash('sha256').update(content).digest('hex');
}

function diffFiles(previous: Array<{ relPath: string; content: Buffer }>, next: PublishFile[]): PublishChanges {
  const before = new Map(previous.map((file) => [file.relPath, sha256(file.content)]));
  const after = new Map(next.map((file) => [file.relPath, sha256(file.content)]));
  const paths = [...new Set([...before.keys(), ...after.keys()])].sort();
  const lines: string[] = [];
  let added = 0; let modified = 0; let deleted = 0;
  for (const path of paths) {
    const oldHash = before.get(path);
    const newHash = after.get(path);
    if (oldHash === undefined && newHash !== undefined) { lines.push(`A ${path}`); added++; }
    else if (oldHash !== undefined && newHash === undefined) { lines.push(`D ${path}`); deleted++; }
    else if (oldHash !== newHash) { lines.push(`M ${path}`); modified++; }
  }
  return { lines, added, modified, deleted };
}

async function buildPublishDiff(opts: {
  previousBundle: Buffer | null;
  nextFiles: PublishFile[];
  keyProvider: ContentKeyProvider;
  logger: Logger;
}): Promise<{ lines: string[]; added: number; modified: number; deleted: number }> {
  if (!opts.previousBundle) return diffFiles([], opts.nextFiles);
  try {
    const { header } = readSealedHeader(opts.previousBundle);
    await opts.keyProvider.ensureKeyAvailable(header.keyId, header.keyserverUrl);
    const contentKey = opts.keyProvider.resolveContentKey(header.keyId, header.keyserverUrl);
    return diffFiles(unsealBundle(opts.previousBundle, contentKey).files, opts.nextFiles);
  } catch (err) {
    opts.logger.warn(`previous sealed bundle could not be decrypted; showing all entries as added: ${err instanceof Error ? err.message : String(err)}`);
    return diffFiles([], opts.nextFiles);
  }
}

async function currentBranch(git: SimpleGit): Promise<string> {
  const local = (await git.raw(['symbolic-ref', '--short', 'HEAD']).catch(() => '')).trim();
  // クラッシュ残骸で HEAD が caveat-publish-tmp 上に乗ったまま残ることがある
  // (checkout --orphan 直後に verifySealedMirror 失敗・kill 等)。これを実 branch
  // と誤認すると以後の remote 照合・push が偽の branch 名で走るため無視する。
  if (local && local !== TMP_BRANCH) return local;
  const remoteHead = await git.raw(['ls-remote', '--symref', 'origin', 'HEAD']).catch(() => '');
  const match = /^ref:\s+refs\/heads\/(.+)\s+HEAD$/m.exec(remoteHead);
  return match?.[1] ?? 'main';
}

async function localHeadSha(git: SimpleGit): Promise<string | null> {
  const sha = (await git.raw(['rev-parse', '--verify', 'HEAD']).catch(() => '')).trim();
  return sha || null;
}

async function remoteBranchSha(git: SimpleGit, branch: string): Promise<string | null> {
  const out = await git.raw(['ls-remote', 'origin', branch]).catch(() => '');
  const first = out.trim().split(/\r?\n/).find(Boolean);
  return first?.split(/\s+/)[0] ?? null;
}

async function checkoutOrphan(git: SimpleGit): Promise<void> {
  // HEAD がクラッシュ残骸で caveat-publish-tmp branch 上に乗ったままだと、
  // 自分が乗っている branch は `branch -D` で削除できず失敗し（catch で握り
  // つぶされる）、続く `checkout --orphan` も同名 branch が既に存在するため
  // 失敗して以後 publish が二度と通らなくなる。事前に detach して tmp branch
  // から外れておく。unborn HEAD の fresh clone では detach 自体が失敗するが、
  // それは既存挙動どおり catch で無視する。
  await git.raw(['checkout', '--detach']).catch(() => '');
  await git.raw(['branch', '-D', TMP_BRANCH]).catch(() => '');
  await git.raw(['checkout', '--orphan', TMP_BRANCH]);
}

async function commitSealedMirror(opts: {
  git: SimpleGit;
  branch: string;
  fileCount: number;
  added: number;
  modified: number;
  deleted: number;
}): Promise<void> {
  await opts.git.add('-A');
  await opts.git.commit(`caveat publish: ${opts.fileCount} public entries (+${opts.added} ~${opts.modified} -${opts.deleted})`);
  await opts.git.raw(['branch', '-M', opts.branch]);
  // history tripwire は push の前に置く: 漏れてから鳴っても手遅れ（remote に history が
  // 露出済み）なので、push で外部に伝播する前に検知して止める。
  const count = Number((await opts.git.raw(['rev-list', '--count', 'HEAD'])).trim());
  if (count !== 1) throw new Error(`publish mirror history verification failed: expected 1 commit, got ${count}`);
  await opts.git.raw(['push', '--force', 'origin', opts.branch]);
  await opts.git.raw(['gc', '--prune=now']).catch(() => '');
}

function readExistingMirror(mirrorDir: string): { readme: string | null; bundle: Buffer | null } {
  const readmePath = join(mirrorDir, 'README.md');
  const bundlePath = join(mirrorDir, BUNDLE_RELPATH);
  return {
    readme: existsSync(readmePath) ? readFileSync(readmePath, 'utf-8') : null,
    bundle: existsSync(bundlePath) ? readFileSync(bundlePath) : null,
  };
}

export async function publishOwn(opts: PublishOwnOptions): Promise<PublishResult> {
  if (!opts.config.publishTarget) throw new Error('publishTarget is not configured');
  if (!opts.config.sealedKeyserverUrl) {
    throw new Error('sealedKeyserverUrl is not configured; deploy a keyserver and set sealedKeyserverUrl in ~/.caveatrc.json. See docs/archive/07 Track B.');
  }
  const collected = collectPublishSet(opts.paths.entriesDir);
  if (collected.invalid.length) throw new Error(`cannot publish invalid entries:\n${collected.invalid.map((x) => `${x.relPath}: ${x.reason}`).join('\n')}`);
  const selfIdentity = publishSelfIdentityTokens();
  // Preserve the pre-scan public API: entriesDir has always been
  // <knowledgeRepo>/entries, so older callers need not supply knowledgeRepo.
  const knowledgeRepo = opts.paths.knowledgeRepo ?? dirname(opts.paths.entriesDir);
  const allow = new Set([...loadPublishAllow(knowledgeRepo), ...(opts.allow ?? [])]);
  const scan = scanPublishFiles(collected.files, { selfIdentity, allow });
  for (const warning of scan.warnings) {
    opts.logger.warn(`publish scan warning: ${warning.relPath}:${warning.line} ${warning.rule} ${warning.excerpt}`);
  }
  if (opts.saveAllow && opts.allow?.length) savePublishAllow(knowledgeRepo, opts.allow);
  if (scan.blocking.length) throw new PublishScanError(scan.blocking);

  // 端末 A/B の設定が trailing slash だけ違うと（正規化前は）bundle header に埋め込まれる
  // keyserverUrl のバイト列が乖離し、内容不変でも changed 判定されて相互 push し合う
  // ping-pong が起きる。seal 前に normalizeKeyserverUrl で揃える。
  const keyserverUrl = normalizeKeyserverUrl(opts.config.sealedKeyserverUrl);
  const keyId = `keyserver:${opts.config.sealedKeyId}`;
  const keyProvider = opts.keyProvider ?? createKeyserverKeyProvider({ caveatHome: opts.paths.caveatHome });
  await keyProvider.ensureKeyAvailable(keyId, keyserverUrl);
  const contentKey = keyProvider.resolveContentKey(keyId, keyserverUrl);
  const bundle = sealBundle({ files: collected.files, contentKey, keyId, keyserverUrl });
  const readme = buildSealedReadme(collected.files.length, collected.files);

  await preparePublishMirror({ mirrorDir: opts.paths.publishMirrorDir, target: opts.config.publishTarget });
  const git = createGit(opts.paths.publishMirrorDir);
  const branch = await currentBranch(git);
  const existing = readExistingMirror(opts.paths.publishMirrorDir);
  const contentChanged = !(existing.bundle?.equals(bundle) === true && existing.readme === readme);
  const [remoteSha, localSha] = await Promise.all([remoteBranchSha(git, branch), localHeadSha(git)]);
  const remoteMatchesLocal = remoteSha !== null && localSha !== null && remoteSha === localSha;
  if (!contentChanged && remoteMatchesLocal) {
    opts.logger.info('no changes to publish');
    return { fileCount: collected.files.length, changed: false, dryRun: Boolean(opts.dryRun) };
  }

  const changes = await buildPublishDiff({ previousBundle: existing.bundle, nextFiles: collected.files, keyProvider, logger: opts.logger });
  for (const line of changes.lines) opts.logger.info(line);
  if (!remoteMatchesLocal) opts.logger.info('remote branch differs or is missing; sealed mirror will be pushed');
  if (opts.dryRun) return { fileCount: collected.files.length, changed: true, dryRun: true };

  const question = `publish ${changes.lines.length} entry change(s)? [y/N]`;
  if (!opts.yes) {
    if (!(opts.isTty ?? (() => Boolean(process.stdin.isTTY)))()) throw new Error(`${question}; rerun with --yes to approve non-interactively`);
    if (!opts.confirmImpl(question)) throw new Error('publish cancelled');
  }

  await checkoutOrphan(git);
  writeSealedMirror({ mirrorDir: opts.paths.publishMirrorDir, bundle, readme });
  const verified = verifySealedMirror({
    mirrorDir: opts.paths.publishMirrorDir,
    bundle,
    contentKey,
    expectedFileCount: collected.files.length,
    readme,
  });
  await commitSealedMirror({
    git,
    branch,
    fileCount: verified.fileCount,
    added: changes.added,
    modified: changes.modified,
    deleted: changes.deleted,
  });
  return { fileCount: verified.fileCount, changed: true, dryRun: false };
}
